/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#121414",
        "surface-dim": "#121414",
        "surface-bright": "#38393a",
        "surface-container-lowest": "#0c0f0f",
        "surface-container-low": "#1a1c1c",
        "surface-container": "#1e2020",
        "surface-container-high": "#282a2b",
        "surface-container-highest": "#333535",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#c4c7c7",
        "background": "#121414",
        "on-background": "#e2e2e2",
        "primary": "#c9c6c5",
        "on-primary": "#313030",
        "secondary": "#e9c176",
        "on-secondary": "#412d00",
        "secondary-container": "#604403",
        "on-secondary-container": "#dab36a",
        "tertiary": "#dec1af",
        "on-tertiary": "#3f2c20",
        "tertiary-container": "#140702",
        "on-tertiary-container": "#8d7565",
        "outline": "#8e9192",
        "outline-variant": "#444748",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "24px",
        "margin-desktop": "80px",
        "gutter": "32px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "section-gap": "160px",
        "container-max": "1440px",
      },
      fontFamily: {
        display: ["Playfair Display", "serif"],
        headline: ["Playfair Display", "serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
